spring:
  application:
    name: config-service
  profiles:
    active: dev
    include: ops


  rabbitmq:
    host: 39.105.64.245
    port: 25672
    username: hchy
    password: 1qazxsw2
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *
